language: cpp

compiler: gcc

os:
    - osx

# use containers
sudo: false

env:
    - TYPE=Release DEVSPACE=$TRAVIS_BUILD_DIR/..

script:
  - cd $DEVSPACE
  - mkdir extra && cd extra
  - git clone --branch=master https://github.com/wxWidgets/wxWidgets.git
  - cd wxWidgets
  - git checkout v3.1.0
  - mkdir -p build$TYPE && cd build$TYPE
  - ../configure --disable-shared --with-libpng=no --with-libjpeg=no --with-libtiff=no --enable-svg=no --with-macosx-version-min=10.9
  - make -j8

before_deploy:
- cd $DEVSPACE/extra
- zip -r -x '*.o' -x '*.gch' -x '*.tlog' -x '*.git*' -q latest.zip wxWidgets
- mkdir -p dpl_cd_upload
- mv latest.zip $DEVSPACE/dpl_cd_upload/wxWidgets-$TRAVIS_OS_NAME.zip
deploy:
  provider: s3
  access_key_id: AKIAJLIJS2MGONMUBW4A
  secret_access_key:
    secure: "v9SFApA3U58zSjNpja1f29dCgwMGVxs1raj9dpso7s4IWaKv0ful7+0Ta7uqh44D1Z48s8nQhz6wHl7aNNbs1JXAPVVFGOFP+at9cvoJOV8imO/pPLxfzz2mbP+0UA4goKb4JoxvJxnS9t48n7d15f/CJqayNwEpOyA2YbPgTsvuhPP8Z/aCwxM+iudSMrgAwZmbcIrUdkFi3zYF5/o0zLHSs13aKbAzRhgF8L3zEiCVHkzGBm37WY4rvHojS9CRhhtKXrYVa1vcZy7+wjhc2eGGNKAApx2nLK3aPlcBt7GOI3Ab3WXAQ9KfEqfjXZm36ta4p6VgVGc9NXj3gzQwXcQjPvD+pAOfnzahyPi3JeF9c9qqFG7AEzwOys06Ps5OqabgRESkwRZxr1FR5W+E4Gc9WmTNyAsGMxdrOhf/GkN6Xi2/2V+J5bodQsTxS302+DaV4E2g/B30H1x5Dtc7hmrIHQy+I2Gq/a+58hA0jFU7MxbKEQab7j3Ck07kTQL8g/prMgNNKMsJ+xyFuSArH95fW1DmEK1UYly0LSTnnOiyhsN6BC7INgYoPJqySelpyhndej/34rPHoXcUfkoVo7IIn8NKRqYHPsQml38/dmwJ9pdMTkDFIoDjIQXCvnkCbpphRTgS5SeqVAtCuehz5PIEDxi3A/guVCJnGAfa9/s="
  bucket: draconpern-buildcache
  acl: public_read
  skip_cleanup: true
  local_dir: dpl_cd_upload
