image: Visual Studio 2013

configuration:
  - Release

install:
  - SET TYPE=%CONFIGURATION%
  - SET DEVSPACE=%APPVEYOR_BUILD_FOLDER%\..

build_script:  
  - cd %DEVSPACE%
  - mkdir extra && cd extra
  - git clone --branch=master https://github.com/wxWidgets/wxWidgets.git
  - set WXWIN=%DEVSPACE%\extra\wxWidgets
  - cd %WXWIN%\build\msw
#  - copy /Y %WXWIN%\include\wx\msw\setup0.h %WXWIN%\include\wx\msw\setup.h
  - powershell "gci . *.vcxproj -recurse | ForEach { (Get-Content $_ | ForEach {$_ -replace 'MultiThreadedDebugDLL', 'MultiThreadedDebug'}) | Set-Content $_ }"
  - powershell "gci . *.vcxproj -recurse | ForEach { (Get-Content $_ | ForEach {$_ -replace 'MultiThreadedDLL', 'MultiThreaded'}) | Set-Content $_ }"
  - msbuild /maxcpucount:2 /P:Configuration=%TYPE% /p:Platform="Win32" wx_vc11.sln

after_build:
  - cd %DEVSPACE%\extra
  - 7z a -xr!*.tlog -xr!*.cpp -xr!*.cc -xr!*.obj -x!*.git* wxWidgets-win.7z wxWidgets
  - mv wxWidgets-win.7z %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: wxWidgets-win.7z
    name: wxWidgets-win

deploy:
  provider: S3
  access_key_id:
    secure: ocfx3RWVSyFaLRBBJXRLrvwqFGoftzrWzqUWrx20/bc=
  secret_access_key:
    secure: cVrRAHZDL4OZaPmgpH2RAa6yKD1ckjrMvtL/RozVMTTxiMWe5+3BKGrWv7RzNQLK
  bucket: draconpern-buildcache
  set_public: true
  folder: 
  artifact: wxWidgets-win